import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 主容器 */}
        <div className="w-black min-h-screen relative">
          {/* 头部 */}
          <div className="w-full h-20 absolute top-0">
            <Header />
          </div>
          {/* 主要内容 */}
          <div className="w-full pt-20 pb-32 h-screen">{children}</div>
          {/* <div className="w-full pt-20 pb-32 h-screen">{children}</div> */}
          {/* footer */}
          <div className="w-full h-32 absolute bottom-0">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
